openapi: 3.2.0
info:
  contact: {}
  title: Infoworks Rest API V3 Stop Streaming API
  version: '1.0'
  description: Infoworks Rest API V3
servers:
- url: '{protocol}://{host}:{port}/v3'
  variables:
    protocol:
      default: http
      enum:
      - http
      - https
    host:
      default: localhost
    port:
      default: '3001'
tags:
- name: StopStreaming
paths:
  /sources/{source_id}/stop-streaming:
    parameters:
    - name: Content-Type
      in: header
      description: Http content type
      required: true
      schema:
        type: string
    - name: source_id
      in: path
      description: Source Id.
      required: true
      schema:
        type: string
    post:
      security:
      - BearerAuth: []
      tags:
      - StopStreaming
      summary: Stops the streaming jobs for tables listed in request.
      description: Stops the streaming jobs for tables listed in request.
      operationId: StopStreaming
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              title: StopStreamingJobRequestSchema
              type: object
              required:
              - table_ids
              properties:
                table_ids:
                  description: Table ids for which streaming needs to be stopped
                  type: array
                  items:
                    type: string
                    example: 5f0754885406f51f04a85293
        required: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Example Success Message
                - type: object
                  properties:
                    result:
                      type: string
                      example: e77850ad5127a2d7dab870ff
        '400':
          description: Request has invalid body or parameters.
          content:
            application/json:
              schema:
                type: object
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Something went wrong
                    details:
                      type: object
                      properties: {}
                - type: object
                  properties:
                    iw_code:
                      type: string
                      example: IW10006
                    help:
                      type: string
                      example: http://api.infoworks.io/help/IW10006
        '401':
          description: Authentication Failed. Please check your Credentials
          content:
            application/json:
              schema:
                type: object
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Something went wrong
                    details:
                      type: object
                      properties: {}
                - type: object
                  properties:
                    iw_code:
                      type: string
                      example: IW10005
                    help:
                      type: string
                      example: http://api.infoworks.io/help/IW10005
        '403':
          description: Forbidden. User lacks access to specified resource.
          content:
            application/json:
              schema:
                type: object
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Something went wrong
                    details:
                      type: object
                      properties: {}
                - type: object
                  properties:
                    iw_code:
                      type: string
                      example: IW10004
                    help:
                      type: string
                      example: http://api.infoworks.io/help/IW10004
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                type: object
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Something went wrong
                    details:
                      type: object
                      properties: {}
                - type: object
                  properties:
                    iw_code:
                      type: string
                      example: IW10002
                    help:
                      type: string
                      example: http://api.infoworks.io/help/IW10002
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      type: http
      scheme: basic
