openapi: 3.2.0
info:
  contact: {}
  title: Infoworks Rest API V3 Validation API
  version: '1.0'
  description: Infoworks Rest API V3
servers:
- url: '{protocol}://{host}:{port}/v3'
  variables:
    protocol:
      default: http
      enum:
      - http
      - https
    host:
      default: localhost
    port:
      default: '3001'
tags:
- name: Validation
  description: ''
paths:
  /validate-entity-names:
    get:
      security:
      - BearerAuth: []
      tags:
      - Validation
      parameters:
      - name: target_type
        in: query
        description: Specify Target Type
        schema:
          type: string
      - name: entity_names
        in: query
        description: Entity names object should be passed as JSON string
        schema:
          type: string
      summary: Use to validate entity names
      description: Use to validate entity names
      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Example Success Message
  /verify-refresh-token:
    put:
      security:
      - BearerAuth: []
      operationId: verifyRefreshToken
      tags:
      - Validation
      summary: Used to verify users refresh token
      description: Used to verify users refresh token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                scheduler_username:
                  type: string
                scheduler_auth_token:
                  type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Example Success Message
        '400':
          description: Request has invalid body or parameters.
          content:
            application/json:
              schema:
                type: object
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Something went wrong
                    details:
                      type: object
                      properties: {}
                - type: object
                  properties:
                    iw_code:
                      type: string
                      example: IW10006
                    help:
                      type: string
                      example: http://api.infoworks.io/help/IW10006
        '401':
          description: Authentication Failed. Please check your Credentials
          content:
            application/json:
              schema:
                type: object
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Something went wrong
                    details:
                      type: object
                      properties: {}
                - type: object
                  properties:
                    iw_code:
                      type: string
                      example: IW10005
                    help:
                      type: string
                      example: http://api.infoworks.io/help/IW10005
        '403':
          description: Forbidden. User lacks access to specified resource.
          content:
            application/json:
              schema:
                type: object
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Something went wrong
                    details:
                      type: object
                      properties: {}
                - type: object
                  properties:
                    iw_code:
                      type: string
                      example: IW10004
                    help:
                      type: string
                      example: http://api.infoworks.io/help/IW10004
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                type: object
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Something went wrong
                    details:
                      type: object
                      properties: {}
                - type: object
                  properties:
                    iw_code:
                      type: string
                      example: IW10002
                    help:
                      type: string
                      example: http://api.infoworks.io/help/IW10002
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      type: http
      scheme: basic
