openapi: 3.2.0
info:
  contact: {}
  title: Infoworks Rest API V3 Favorites API
  version: '1.0'
  description: Infoworks Rest API V3
servers:
- url: '{protocol}://{host}:{port}/v3'
  variables:
    protocol:
      default: http
      enum:
      - http
      - https
    host:
      default: localhost
    port:
      default: '3001'
tags:
- name: Favorites
paths:
  /sources/favorites/check-favorite:
    get:
      security:
      - BearerAuth: []
      tags:
      - Favorites
      summary: Check entity favorite tag
      description: Check entity favorite tag
      parameters:
      - name: entity_id
        in: query
        description: Entity ID
        required: true
        schema:
          type: string
      - name: entity_type
        in: query
        description: Entity Type
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Example Success Message
                - type: object
                  properties:
                    is_favorite:
                      type: boolean
                      example: true
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Something went wrong
                        detail:
                          type: object
                          properties: {}
                        help:
                          type: string
                          example: https://docs.infoworks.io/api/errors/IW1004
                        code:
                          type: string
                          example: IW1004
        '401':
          description: Unauthorized Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Something went wrong
                        detail:
                          type: object
                          properties: {}
                        help:
                          type: string
                          example: https://docs.infoworks.io/api/errors/IW1004
                        code:
                          type: string
                          example: IW1004
        '403':
          description: Forbidden Access
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Something went wrong
                        detail:
                          type: object
                          properties: {}
                        help:
                          type: string
                          example: https://docs.infoworks.io/api/errors/IW1004
                        code:
                          type: string
                          example: IW1004
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Something went wrong
                        detail:
                          type: object
                          properties: {}
                        help:
                          type: string
                          example: https://docs.infoworks.io/api/errors/IW1004
                        code:
                          type: string
                          example: IW1004
  /sources/favorites/toggle-favorite:
    patch:
      security:
      - BearerAuth: []
      tags:
      - Favorites
      summary: Toggle entity favorite tag
      description: Toggle entity favorite tag
      parameters:
      - name: entity_id
        in: query
        description: Entity ID
        required: true
        schema:
          type: string
      - name: entity_type
        in: query
        description: Entity Type
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Example Success Message
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Something went wrong
                        detail:
                          type: object
                          properties: {}
                        help:
                          type: string
                          example: https://docs.infoworks.io/api/errors/IW1004
                        code:
                          type: string
                          example: IW1004
        '401':
          description: Unauthorized Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Something went wrong
                        detail:
                          type: object
                          properties: {}
                        help:
                          type: string
                          example: https://docs.infoworks.io/api/errors/IW1004
                        code:
                          type: string
                          example: IW1004
        '403':
          description: Forbidden Access
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Something went wrong
                        detail:
                          type: object
                          properties: {}
                        help:
                          type: string
                          example: https://docs.infoworks.io/api/errors/IW1004
                        code:
                          type: string
                          example: IW1004
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Something went wrong
                        detail:
                          type: object
                          properties: {}
                        help:
                          type: string
                          example: https://docs.infoworks.io/api/errors/IW1004
                        code:
                          type: string
                          example: IW1004
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      type: http
      scheme: basic
