openapi: 3.2.0
info:
  contact: {}
  title: Infoworks Rest API V3 Clear Cache API
  version: '1.0'
  description: Infoworks Rest API V3
servers:
- url: '{protocol}://{host}:{port}/v3'
  variables:
    protocol:
      default: http
      enum:
      - http
      - https
    host:
      default: localhost
    port:
      default: '3001'
tags:
- name: Clear Cache
paths:
  /admin/clear-cache:
    post:
      security:
      - BearerAuth: []
      tags:
      - Clear Cache
      summary: To clear Admin cache
      description: To clear Admin cache
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: adbc@gmail.com
      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Example Success Message
        '400':
          description: Request has invalid body or parameters.
          content:
            application/json:
              schema:
                type: object
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Something went wrong
                    details:
                      type: object
                      properties: {}
                - type: object
                  properties:
                    iw_code:
                      type: string
                      example: IW10006
                    help:
                      type: string
                      example: http://api.infoworks.io/help/IW10006
        '401':
          description: Authentication Failed. Please check your Credentials
          content:
            application/json:
              schema:
                type: object
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Something went wrong
                    details:
                      type: object
                      properties: {}
                - type: object
                  properties:
                    iw_code:
                      type: string
                      example: IW10005
                    help:
                      type: string
                      example: http://api.infoworks.io/help/IW10005
        '403':
          description: Forbidden. User lacks access to specified resource.
          content:
            application/json:
              schema:
                type: object
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Something went wrong
                    details:
                      type: object
                      properties: {}
                - type: object
                  properties:
                    iw_code:
                      type: string
                      example: IW10004
                    help:
                      type: string
                      example: http://api.infoworks.io/help/IW10004
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                type: object
                allOf:
                - type: object
                  properties:
                    message:
                      type: string
                      example: Something went wrong
                    details:
                      type: object
                      properties: {}
                - type: object
                  properties:
                    iw_code:
                      type: string
                      example: IW10002
                    help:
                      type: string
                      example: http://api.infoworks.io/help/IW10002
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      type: http
      scheme: basic
